import { test, expect } from '@playwright/test';
for (const width of [320, 390, 1440]) {
  test(`composer Redo stays reachable and preserves the unsent draft at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 844 });
    await page.goto('/?demo=1');
    await page.getByRole('button', { name: /The Lantern Hollow/ }).click();
    await page.getByRole('button', { name: 'Begin adventure', exact: true }).click();
    const redo = page.getByRole('button', { name: 'Redo', exact: true });
    await expect(redo).toBeDisabled();
    await expect(redo).toBeInViewport();
    await page.getByLabel('Your action').fill('follow the silver bird');
    await page.getByRole('button', { name: 'Send action' }).click();
    await expect(redo).toBeDisabled();
    await expect(redo).toBeEnabled({ timeout: 20000 });
    const before = await page.evaluate(() => JSON.parse(localStorage.getItem('wayfarer-demo-v1')!).adventures[0]);
    await page.getByRole('button', { name: 'Say', exact: true }).click();
    await page.getByLabel('Your action').fill('keep this unsent draft');
    await redo.click();
    await expect(redo).toBeDisabled();
    await expect(redo).toBeEnabled({ timeout: 20000 });
    const after = await page.evaluate(() => JSON.parse(localStorage.getItem('wayfarer-demo-v1')!).adventures[0]);
    expect(after.turns).toHaveLength(1);
    expect(after.turns[0].id).not.toBe(before.turns[0].id);
    expect(after.turns[0].input).toBe('follow the silver bird');
    expect(after.turns[0].mode).toBe('do');
    await expect(page.getByLabel('Your action')).toHaveValue('keep this unsent draft');
    await expect(page.getByRole('button', { name: 'Say', exact: true })).toHaveAttribute('aria-pressed', 'true');
    await expect(redo).toBeInViewport();
    await expect(page.locator('body')).toHaveJSProperty('scrollWidth', width);
    await page.screenshot({ path: `artifacts/redo-composer-${width}.png` });
    await page.getByLabel('Your action').fill('   ');
    await page.getByRole('button', { name: 'Continue story', exact: true }).click();
    await expect(redo).toBeEnabled({ timeout: 20000 });
    const continued = await page.evaluate(() => JSON.parse(localStorage.getItem('wayfarer-demo-v1')!).adventures[0]);
    expect(continued.turns).toHaveLength(2);
    expect(continued.turns[0]).toEqual(after.turns[0]);
    expect(continued.turns[1]).toMatchObject({ mode: 'continue', input: '' });
    if (width === 390) {
      await page.getByLabel('Your action').press('Control+Enter');
      await expect(redo).toBeEnabled({ timeout: 20000 });
      const keyboard = await page.evaluate(() => JSON.parse(localStorage.getItem('wayfarer-demo-v1')!).adventures[0]);
      expect(keyboard.turns).toHaveLength(3);
      expect(keyboard.turns[2]).toMatchObject({ mode: 'continue', input: '' });
    }
    await page.reload();
    await page.getByRole('button', { name: /The Lantern Hollow.*turns into your story/ }).click();
    await expect(redo).toBeEnabled();
  });
}

test('mobile creation, AI draft, play, undo, reload and exact-card imports', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/?demo=1');
  await expect(page.getByRole('heading', { name: 'Where to next?' })).toBeVisible();
  await page.screenshot({ path: 'artifacts/mobile-discover.png', fullPage: true });
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth', 390);
  await page.getByRole('button', { name: 'Create a scenario', exact: true }).click();
  await page.getByRole('button', { name: 'Create with AI', exact: true }).click();
  await page.getByLabel('Your idea').fill('A clockwork garden');
  await page.getByRole('button', { name: 'Generate scenario', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Use this draft' })).toBeEnabled({ timeout: 20000 });
  const aiDraft = JSON.parse(await page.getByRole('textbox', { name: 'Draft JSON', exact: true }).inputValue());
  aiDraft.instructions = 'Keep a playful tone.';
  await page.getByRole('textbox', { name: 'Draft JSON', exact: true }).fill(JSON.stringify(aiDraft));
  await page.getByRole('button', { name: 'Review edited JSON', exact: true }).click();
  await page.getByRole('button', { name: 'Use this draft' }).click();
  await expect(page.getByRole('textbox', { name: /^AI instructions/ })).toHaveValue(/Never invent the player's actions/);
  await expect(page.getByRole('textbox', { name: /^AI instructions/ })).toHaveValue(/Never offer suggested actions/);
  await expect(page.getByRole('textbox', { name: /^AI instructions/ })).toHaveValue(/Do not repeat, recap/);
  await expect(page.getByRole('textbox', { name: /^AI instructions/ })).toHaveValue(/Keep a playful tone/);
  await page.getByRole('button', { name: /Story cards ·/ }).click();
  await page.getByRole('button', { name: 'Import cards', exact: true }).click();
  const notes = '  {"mind":"Exact brain"}\r\n\t ';
  await page.getByLabel('Or paste JSON').fill(JSON.stringify([{ title: 'Finch', keys: 'Finch', value: 'Finch is a fox.', description: notes, useForCharacterCreation: true, custom: 42 }]));
  await page.getByRole('button', { name: 'Import 1 cards', exact: true }).click();
  await page.getByRole('button', { name: 'Save & play', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'The Clockwork Garden', exact: true }).first()).toBeVisible();
  await page.getByRole('textbox', { name: 'Your action' }).fill('greet Finch');
  await page.getByRole('button', { name: 'Send action', exact: true }).click();
  await expect(page.getByText('1 turns · Saved on this device', { exact: true })).toBeVisible({ timeout: 20000 });
  await page.screenshot({ path: 'artifacts/mobile-adventure.png', fullPage: true });
  await page.getByRole('button', { name: 'Redo', exact: true }).click();
  await expect(page.getByText('1 turns · Saved on this device', { exact: true })).toBeVisible({ timeout: 20000 });
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(page.getByText('0 turns · Saved on this device', { exact: true })).toBeVisible();
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('wayfarer-demo-v1')!));
  expect(saved.adventures[0].cards[0].fields.description).toBe(notes);
  expect(saved.adventures[0].cards[0].fields.custom).toBe(42);
  await page.reload();
  await page.getByRole('button', { name: /The Clockwork Garden.*0 turns into your story/ }).click();
  await expect(page.getByText('0 turns · Saved on this device', { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});
test('real worker runs Inner Self in the single app UI', async ({ page }) => {
  await page.goto('/?demo=1');
  await page.getByRole('button', { name: 'The Lantern Hollow', exact: false }).click();
  await page.getByRole('button', { name: 'Edit', exact: true }).click();
  await page.getByRole('button', { name: 'Scripts', exact: true }).click();
  await page.getByRole('button', { name: /Inner Self NPC minds/ }).click();
  await page.getByRole('button', { name: 'Load preset', exact: true }).click();
  await page.getByRole('button', { name: 'Save & play', exact: true }).click();
  await page.getByRole('button', { name: 'Continue story', exact: true }).click();
  await expect(page.getByText('1 turns · Saved on this device', { exact: true })).toBeVisible({ timeout: 30000 });
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('wayfarer-demo-v1')!));
  expect(saved.adventures[0].cards.some((c: any) => c.fields.title.includes('Inner Self'))).toBe(true);
});
test('desktop and production outside Layla show honest availability', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 960 });
  await page.goto('/');
  await expect(page.getByText('Browser workspace', { exact: true })).toBeVisible();
  await page.screenshot({ path: 'artifacts/desktop-discover.png', fullPage: true });
  await page.getByRole('button', { name: 'The Lantern Hollow', exact: false }).click();
  await page.getByRole('button', { name: 'Begin adventure', exact: true }).click();
  await page.getByRole('button', { name: 'Continue story', exact: true }).click();
  await expect(page.getByText(/Open Wayfarer inside Layla to generate/)).toBeVisible();
});

test('nested glass dialogs keep the card editor and its actions reachable', async ({ page }) => {
  await page.goto('/?demo=1');
  await page.getByRole('button', { name: /The Lantern Hollow/ }).click();
  await page.getByRole('button', { name: 'Begin adventure', exact: true }).click();
  await page.getByRole('button', { name: 'Adventure menu', exact: true }).click();
  await page.getByRole('button', { name: 'Story cards', exact: true }).click();
  await page.getByRole('button', { name: 'Edit Finch', exact: true }).click();
  const editor = page.getByRole('dialog', { name: 'Edit story card', exact: true });
  await expect(editor.getByRole('heading', { name: 'Edit story card' })).toBeInViewport();
  await expect(editor.getByRole('button', { name: 'Save card' })).toBeInViewport();
  await page.keyboard.press('Escape');
  await expect(editor).toHaveCount(0);
  await expect(page.getByRole('dialog', { name: 'Story cards', exact: true })).toBeVisible();
});
