import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser = await chromium.launch();
const page = await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});
const issues=[]; page.on('pageerror', e=>issues.push(e.message));
const capture=async name=>{await page.screenshot({path:`artifacts/neo-${name}.png`});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Overflow on ${name}`)};
await page.goto('http://127.0.0.1:5173/?demo=1');
await page.getByRole('heading',{name:'Where to next?'}).waitFor();
await capture('mobile-home');
await page.locator('.mobile-nav').getByRole('button',{name:'Scenarios',exact:true}).click();
await capture('mobile-scenarios');
await page.getByRole('button',{name:/The Lantern Hollow/}).click();
await capture('mobile-scenario-dialog');
await page.getByRole('button',{name:'Edit',exact:true}).click();
await capture('mobile-editor');
await page.getByRole('button',{name:/Story cards ·/}).click();
await capture('mobile-editor-cards');
await page.getByRole('button',{name:'New card',exact:true}).click();
await capture('mobile-card-editor');
await page.getByRole('button',{name:'Close dialog',exact:true}).click();
await page.getByRole('button',{name:'Scripts',exact:true}).click();
await capture('mobile-scripts');
await page.getByRole('button',{name:'Save & play',exact:true}).click();
await capture('mobile-story');
await page.getByLabel('Your action').fill('Follow the lanterns.');
assert(await page.getByRole('button',{name:'Send action',exact:true}).isEnabled());
await page.getByRole('button',{name:'Say',exact:true}).click();
await capture('mobile-composer');
await page.getByRole('button',{name:'Adventure menu',exact:true}).click();
await capture('mobile-story-menu');
await page.getByRole('button',{name:'Adventure memory',exact:true}).click();
await capture('mobile-memory');
await page.getByRole('button',{name:'Close dialog',exact:true}).click();
await page.getByRole('button',{name:'Back to adventures',exact:true}).click();
await capture('mobile-adventures');
await page.locator('.mobile-nav').getByRole('button',{name:'Settings',exact:true}).click();
await capture('mobile-settings');
await page.locator('.mobile-nav').getByRole('button',{name:'Discover',exact:true}).click();
await capture('mobile-home-resume');
for(const width of [320,360,768,1440]){
  await page.setViewportSize({width,height:900});
  await capture(`home-${width}`);
  await page.locator(width<=850?'.mobile-nav':'.sidebar nav').getByRole('button',{name:'Scenarios',exact:true}).click();
  await capture(`scenarios-${width}`);
  await page.getByRole('button',{name:/The Lantern Hollow/}).click();
  await page.getByRole('button',{name:'Edit',exact:true}).click();
  await capture(`editor-${width}`);
  await page.locator(width<=850?'.mobile-nav':'.sidebar nav').getByRole('button',{name:'Discover',exact:true}).click();
}
assert.deepEqual(issues,[]);
console.log('Visual review: 26 captures, no horizontal overflow at 320, 360, 390, 768 or 1440px; no page errors.');
await browser.close();
