import { useState } from 'react';
import { Plus, Search, FileDown, FileUp, Sparkles, Pin, Pencil, Trash2, Check, ScrollText } from 'lucide-react';
import { type Card, type Scenario, cardTitle, clone } from './domain';
import { blankCard, exportCards, importCards, mergeCards, type CardImport, type MergeMode } from './cards';
import { downloadJson, generateJson } from './host';
import { Empty, Field, Modal } from './ui';

export function CardManager({ cards, onChange, world, report }: { cards: Card[]; onChange: (cards: Card[]) => void; world: Pick<Scenario, 'title' | 'memory'>; report: (message: string) => void }) {
  const [search, setSearch] = useState(''), [editing, setEditing] = useState<Card | null>(null), [importing, setImporting] = useState(false), [generating, setGenerating] = useState(false);
  const [source, setSource] = useState(''), [result, setResult] = useState<CardImport | null>(null), [merge, setMerge] = useState<MergeMode>('skip'), [error, setError] = useState('');
  const filtered = cards.filter(c => `${cardTitle(c)} ${c.fields.keys} ${c.fields.type}`.toLowerCase().includes(search.toLowerCase()));
  const parse = (text: string) => { setSource(text); setError(''); try { setResult(importCards(text)); } catch (e) { setResult(null); setError((e as Error).message); } };
  return <section className="card-manager">
    <div className="section-copy"><p>People, places, and the details that make a world yours.</p><small>Entries enter the story when a trigger matches. Notes stay private unless a script uses them.</small></div>
    <div className="toolbar"><button className="button primary" onClick={() => setEditing(blankCard())}><Plus size={17}/>New card</button><button className="button" onClick={() => setGenerating(true)}><Sparkles size={16}/>Generate</button><button className="icon-button" title="Import cards" aria-label="Import cards" onClick={() => { setImporting(true); setResult(null); setSource(''); setError(''); }}><FileUp size={18}/></button><button className="icon-button" title="Export cards" aria-label="Export cards" onClick={() => downloadJson('wayfarer-story-cards.json', exportCards(cards)).catch(e => report(e.message))}><FileDown size={18}/></button></div>
    {!!cards.length && <div className="search"><Search size={18}/><input aria-label="Search story cards" placeholder={`Search ${cards.length} cards…`} value={search} onChange={e => setSearch(e.target.value)}/></div>}
    <div className="lore-list">{filtered.map(c => <article className={'lore-row ' + (!c.enabled ? 'muted-card' : '')} key={c.uid}><span className="lore-icon"><ScrollText size={19}/></span><button className="lore-main" onClick={() => setEditing(clone(c))}><span className="eyebrow">{c.fields.type || 'Lore'}{c.pinned && ' · Always included'}</span><h3>{cardTitle(c)}</h3><p>{c.fields.value || 'No narrative entry'}</p></button><button className="icon-button" aria-label={`Edit ${cardTitle(c)}`} onClick={() => setEditing(clone(c))}><Pencil size={16}/></button></article>)}</div>
    {!filtered.length && <Empty icon={<ScrollText/>} title={search ? 'No matching cards' : 'Every world has its lore'} text={search ? 'Try a different name or trigger.' : 'Add a character, a place, or a rule. Your cards will follow the story.'}/>}
    {editing && <Modal title={cards.some(c => c.uid === editing.uid) ? 'Edit story card' : 'New story card'} onClose={() => setEditing(null)}><form onSubmit={e => { e.preventDefault(); onChange(cards.some(c => c.uid === editing.uid) ? cards.map(c => c.uid === editing.uid ? editing : c) : [...cards, editing]); setEditing(null); }}>
      <div className="form-body"><Field label="Title"><input required value={editing.fields.title ?? ''} onChange={e => setEditing({ ...editing, fields: { ...editing.fields, title: e.target.value } })} placeholder="A name worth remembering"/></Field><div className="form-grid"><Field label="Type"><input list="card-types" value={editing.fields.type ?? ''} onChange={e => setEditing({ ...editing, fields: { ...editing.fields, type: e.target.value } })}/><datalist id="card-types"><option value="character"/><option value="location"/><option value="faction"/><option value="item"/><option value="world rule"/><option value="custom"/></datalist></Field><Field label="Triggers" hint="Separate words or names with commas."><input value={editing.fields.keys} onChange={e => setEditing({ ...editing, fields: { ...editing.fields, keys: e.target.value } })} placeholder="Finch, stationmaster"/></Field></div>
      <Field label="Entry" hint="Lore the narrator may use."><textarea rows={5} value={editing.fields.value} onChange={e => setEditing({ ...editing, fields: { ...editing.fields, value: e.target.value } })}/></Field>
      <Field label="Notes" hint="Exact notes and script data are preserved, including whitespace."><textarea className="code" rows={6} value={editing.fields.description ?? ''} onChange={e => setEditing({ ...editing, fields: { ...editing.fields, description: e.target.value } })}/></Field>
      <label className="check-row"><input type="checkbox" checked={editing.enabled} onChange={e => setEditing({ ...editing, enabled: e.target.checked })}/>Enable for narrative context</label><label className="check-row"><input type="checkbox" checked={editing.pinned} onChange={e => setEditing({ ...editing, pinned: e.target.checked })}/><Pin size={15}/>Always include entry when space allows</label><label className="check-row"><input type="checkbox" checked={!!(editing.fields.useForCharacterCreation ?? editing.fields.useForCharacterCreator)} onChange={e => setEditing({ ...editing, fields: { ...editing.fields, useForCharacterCreation: e.target.checked, ...(Object.hasOwn(editing.fields, 'useForCharacterCreator') ? { useForCharacterCreator: e.target.checked } : {}) } })}/>Available for character creation (export flag)</label></div>
      <footer className="modal-actions">{cards.some(c => c.uid === editing.uid) && <button type="button" className="button danger" onClick={() => { onChange(cards.filter(c => c.uid !== editing.uid)); setEditing(null); }}><Trash2 size={16}/>Delete</button>}<button className="button primary" type="submit"><Check size={17}/>Save card</button></footer></form></Modal>}
    {importing && <Modal title="Import story cards" onClose={() => setImporting(false)}><div className="form-body"><p>Import an AI Dungeon JSON export. All notes, flags, and extra fields stay intact.</p><label className="file-drop"><FileUp/><span>Choose a JSON file</span><input type="file" accept=".json,application/json" onChange={async e => { const f = e.target.files?.[0]; if (f) { if (f.size > 10 * 1024 * 1024) setError('File is larger than 10 MB.'); else parse(await f.text()); } }}/></label><Field label="Or paste JSON"><textarea className="code" rows={6} value={source} onChange={e => parse(e.target.value)} placeholder={'[{"keys":"Finch","value":"A fox stationmaster…"}]'}/></Field><Field label="When cards overlap"><select value={merge} onChange={e => setMerge(e.target.value as MergeMode)}><option value="skip">Skip fully identical cards; keep different notes</option><option value="keep">Keep every card as a new copy</option><option value="update">Update matching title + triggers</option></select></Field>{merge === 'update' && <p className="notice">Matching cards will take all fields from the import, including notes.</p>}{error && <p role="alert" className="error">{error}</p>}{result && <div className="notice"><strong>{result.cards.length} valid / {result.total} total</strong>{result.errors.map((e, i) => <p key={i}>{e}</p>)}{result.warnings.map((e, i) => <p key={i}>{e}</p>)}</div>}</div><footer className="modal-actions"><button className="button primary" disabled={!result?.cards.length} onClick={() => { const merged = mergeCards(cards, result!.cards, merge); onChange(merged.cards); report(`${merged.added} added · ${merged.updated} updated · ${merged.skipped} identical cards skipped`); setImporting(false); }}>Import {result?.cards.length || ''} cards</button></footer></Modal>}
    {generating && <CardGenerator world={world} onClose={() => setGenerating(false)} onUse={generated => { onChange([...cards, ...generated]); setGenerating(false); report(`${generated.length} story cards added`); }}/>}</section>;
}

function CardGenerator({ world, onClose, onUse }: { world: Pick<Scenario, 'title' | 'memory'>; onClose: () => void; onUse: (cards: Card[]) => void }) {
  const [prompt, setPrompt] = useState(''), [raw, setRaw] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState(''), [preview, setPreview] = useState<Card[] | null>(null), [controller] = useState(() => new AbortController());
  const review = () => { try { const result = importCards(raw); if (result.errors.length) throw new Error(result.errors.join('\n')); setPreview(result.cards); setError(''); } catch(e) { setError((e as Error).message); } };
  return <Modal title="Dream up some lore" onClose={() => { controller.abort(); onClose(); }}><div className="form-body"><p>Describe the characters, places, or ideas you need. Review the draft before adding it.</p><Field label="What should we create?"><textarea rows={3} value={prompt} onChange={e => setPrompt(e.target.value)} placeholder="A suspicious innkeeper and the secret society they belong to…"/></Field><button className="button primary" disabled={busy || !prompt.trim()} onClick={async () => { setBusy(true); setError(''); setPreview(null); try { const data = await generateJson(`WAYFARER_CARDS_JSON\nReturn only a JSON array of up to 5 story cards with string title, keys (comma-separated triggers), value (narrative lore), type and description (private notes). World: ${world.title}\n${world.memory}\nRequest: ${prompt}`, setRaw, controller.signal); setRaw(JSON.stringify(data, null, 2)); const result = importCards(JSON.stringify(data)); if (result.errors.length) throw new Error(result.errors.join('\n')); setPreview(result.cards); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}><Sparkles size={17}/>{busy ? 'Imagining…' : 'Generate cards'}</button>{raw && <Field label="Editable draft JSON"><textarea className="code" rows={10} value={raw} onChange={e => { setRaw(e.target.value); setPreview(null); }}/></Field>}{error && <p className="error" role="alert">{error}</p>}{raw && !busy && <button className="button" onClick={review}>Validate edited draft</button>}{preview && <p className="notice">Ready to add: {preview.map(cardTitle).join(', ')}</p>}</div><footer className="modal-actions"><button className="button primary" disabled={!preview?.length || busy} onClick={() => onUse(preview!)}>Add {preview?.length || ''} cards</button></footer></Modal>;
}
