import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowUp, BookOpen, Check, ChevronDown, Code2, FileDown, Link2, MessageCircle, MoreHorizontal, Pencil, RefreshCw, ScrollText, Settings2, Square, Undo2, WandSparkles } from 'lucide-react';
import type { LaylaCharacter } from '@layla-network/sdk';
import { type Adventure, type Mode, type Settings, clone, undoTurn, visibleText } from './domain';
import { processTurn } from './engine';
import { runHook } from './scripts/client';
import { downloadJson, generate, hasNativeBridge, layla, memoryProjections, recallMemories, syncMemories, withTimeout } from './host';
import { CardManager } from './CardManager';
import { Field, Modal, Scene } from './ui';
import { buildContext } from './context';

const modes = [{ id: 'do', name: 'Do', Icon: WandSparkles, placeholder: 'What do you do next?' }, { id: 'say', name: 'Say', Icon: MessageCircle, placeholder: 'What do you say?' }, { id: 'story', name: 'Story', Icon: Pencil, placeholder: 'Add something to the story…' }] as const;
export function Play({ adventure, settings, onChange, onBack, onEdit, onBusy, report }: { adventure: Adventure; settings: Settings; onChange: (a: Adventure) => Promise<void>; onBack: () => void; onEdit: () => void; onBusy: (busy: boolean) => void; report: (s: string) => void }) {
  const [mode, setMode] = useState<Mode>('do'), [input, setInput] = useState(''), [busy, setBusy] = useState(false), [status, setStatus] = useState(''), [streaming, setStreaming] = useState(''), [error, setError] = useState('');
  const [panel, setPanel] = useState<'cards' | 'memory' | 'inspect' | null>(null), [editText, setEditText] = useState<string | null>(null), [menu, setMenu] = useState(false);
  const controller = useRef<AbortController | null>(null), end = useRef<HTMLDivElement>(null), latest = adventure.turns.at(-1);
  useEffect(() => () => { controller.current?.abort(); }, []);
  useEffect(() => { if (busy) end.current?.scrollIntoView({ behavior: 'smooth', block: 'end' }); }, [busy]);
  async function act(action: Mode, retry = false) {
    if (busy) return;
    const abort = new AbortController(); controller.current = abort; setBusy(true); onBusy(true); setError(''); setStreaming(''); setMenu(false);
    try {
      let recalledCardIds: string[] = [];
      if (adventure.memoryBinding) {
        setStatus('Finding this adventure’s memories…');
        try { const memories = await recallMemories(adventure, abort.signal); const projections = memoryProjections(adventure); recalledCardIds = memories.map(m => projections.find(p => p.raw === m.rawText)?.key).filter((id): id is string => !!id); }
        catch { if (!abort.signal.aborted) report('Layla memory recall is unavailable. Using this adventure’s saved lore.'); }
      }
      const next = await processTurn({ adventure, mode: action, input: action === 'continue' ? '' : input, settings, signal: abort.signal, generate, runHook, onText: setStreaming, onStatus: setStatus, retry, recalledCardIds });
      await onChange(next); if (!retry) setInput('');
      if (!visibleText(next.turns.at(-1)?.output || '')) report('Script state updated. Continue when you’re ready.');
      requestAnimationFrame(() => end.current?.scrollIntoView({ behavior: 'smooth', block: 'end' }));
    } catch(e) { if (abort.signal.aborted) report('Generation cancelled. Your last saved turn is intact.'); else setError((e as Error).message); }
    finally { setBusy(false); onBusy(false); setStreaming(''); setStatus(''); controller.current = null; }
  }
  return <div className="play-page"><header className="play-header"><button disabled={busy} className="icon-button" aria-label="Back to adventures" onClick={onBack}><ArrowLeft size={20}/></button><div><h1>{adventure.title}</h1><span>{busy ? 'A new moment is unfolding' : `${adventure.turns.length} turns · Saved on this device`}</span></div><button className="icon-button" disabled={busy} aria-label="Adventure menu" onClick={() => setMenu(!menu)}><MoreHorizontal size={23}/></button></header>{menu && <div className="popover"><button onClick={() => { setPanel('cards'); setMenu(false); }}><ScrollText size={17}/>Story cards</button><button onClick={() => { setPanel('memory'); setMenu(false); }}><BookOpen size={17}/>Adventure memory</button><button onClick={() => { setPanel('inspect'); setMenu(false); }}><Code2 size={17}/>Context & script logs</button><button onClick={onEdit}><Settings2 size={17}/>Adventure settings</button><button onClick={() => { downloadJson('wayfarer-transcript.json', JSON.stringify({ title: adventure.title, opening: adventure.opening, turns: adventure.turns.map(t => ({ mode: t.mode, input: t.input, output: t.output })) }, null, 2)).catch(e => report(e.message)); setMenu(false); }}><FileDown size={17}/>Export transcript</button></div>}
    <div className="story-column" style={{ '--story-size': `${settings.fontSize}px` } as React.CSSProperties}><div className="story-opening"><div className="story-banner"><Scene theme={adventure.theme}/><div><span className="eyebrow">{adventure.genre} · Chapter one</span><h2>{adventure.title}</h2></div></div><div className="prose">{adventure.opening}</div></div>{adventure.turns.map((turn, index) => <article className="story-turn" key={turn.id}>{turn.mode !== 'continue' && <div className="player-action"><span>{turn.mode === 'say' ? <MessageCircle size={16}/> : turn.mode === 'story' ? <Pencil size={16}/> : <WandSparkles size={16}/>}</span><p>{turn.mode === 'say' ? `“${turn.input}”` : turn.mode === 'do' ? `You ${turn.input}` : turn.input}</p></div>}{visibleText(turn.output) ? <div className={'prose ' + (/^\s*>>>/.test(turn.output) ? 'script-message' : '')}>{turn.output}</div> : <div className="turn-note"><Check size={14}/>{turn.stopped ? 'Script paused this turn.' : 'World state updated.'}</div>}{index === adventure.turns.length - 1 && <div className="turn-actions"><button disabled={busy} onClick={() => setEditText(turn.output)}><Pencil size={14}/>Edit</button><button disabled={busy} onClick={() => onChange(undoTurn(adventure)).catch(e => setError(e.message))}><Undo2 size={14}/>Undo</button></div>}</article>)}{busy && <div className="generation"><div className="writing-status" role="status"><span className="pulse-dot"/>{status}</div>{streaming && <div className="prose">{streaming}<span className="caret"/></div>}{adventure.scripts.enabled && <small>Applying the script’s changes before revealing the passage.</small>}</div>}{typeof adventure.state.message === 'string' && adventure.state.message && <p className="notice">{adventure.state.message}</p>}{error && <div className="error" role="alert"><strong>The turn wasn’t saved.</strong><p>{error}</p><button className="button" onClick={() => setError('')}>Dismiss</button></div>}<div ref={end}/></div>
    <div className="composer-wrap"><div className="composer"><div className="composer-top"><div className="action-modes">{modes.map(m => <button key={m.id} disabled={busy} aria-pressed={mode === m.id} className={mode === m.id ? 'active' : ''} onClick={() => setMode(m.id)}><m.Icon size={15}/>{m.name}</button>)}</div><button className="continue redo" disabled={busy || !latest} title={latest ? 'Regenerate the last turn using the same action' : 'Send a turn first to enable Redo'} onClick={() => { if (latest) act(latest.mode, true); }}><RefreshCw size={14}/>Redo</button></div><form onSubmit={e => { e.preventDefault(); act(input.trim() ? mode : 'continue'); }}><textarea aria-label="Your action" rows={2} value={input} maxLength={12000} disabled={busy} onChange={e => setInput(e.target.value)} placeholder={modes.find(m => m.id === mode)?.placeholder} onKeyDown={e => { if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) { e.preventDefault(); act(input.trim() ? mode : 'continue'); } }}/>{busy ? <button className="send cancel" type="button" aria-label="Cancel generation" onClick={() => controller.current?.abort()}><Square size={16}/></button> : <button className="send" type="submit" aria-label={input.trim() ? 'Send action' : 'Continue story'} title={input.trim() ? 'Send action' : 'Continue the story'}><ArrowUp size={21}/></button>}</form></div><div className="composer-foot"><span>{adventure.scripts.enabled ? 'Scripts on · ' : ''}Your choices shape the story.</span><button disabled={busy} onClick={() => setPanel('cards')}><ScrollText size={13}/>{adventure.cards.length} cards</button></div></div>
    {panel && <Modal title={panel === 'cards' ? 'Story cards' : panel === 'memory' ? 'Adventure memory' : 'Behind the story'} wide onClose={() => setPanel(null)}><div className="form-body">{panel === 'cards' ? <CardManager world={adventure} cards={adventure.cards} onChange={cards => onChange({ ...adventure, cards }).catch(e => report(e.message))} report={report}/> : panel === 'memory' ? <MemoryPanel adventure={adventure} onChange={onChange} report={report}/> : <><p className="subtle">Context uses current facts and triggered entries. Notes are available to scripts, but ordinary notes never enter narration automatically.</p><details open><summary>Current context preview</summary><pre className="inspect">{buildContext(adventure, '', settings).text}</pre></details><details><summary>Last turn’s script logs</summary><pre className="inspect">{latest?.logs.join('\n') || 'No script logs yet.'}</pre></details><details><summary>Persistent script state</summary><pre className="inspect">{JSON.stringify(adventure.state, null, 2)}</pre></details><p className="subtle">This preview precedes the Context hook. Scripts can replace or restructure it at generation time.</p></>}</div></Modal>}
    {editText !== null && <Modal title="Edit the latest passage" onClose={() => setEditText(null)}><div className="form-body"><Field label="Story text"><textarea rows={12} value={editText} onChange={e => setEditText(e.target.value)}/></Field>{adventure.scripts.enabled && <p className="subtle">This edits the visible passage. Use Undo to also roll back NPC/card state, then submit a new action.</p>}</div><footer className="modal-actions"><button className="button primary" onClick={async () => { const copy = clone(adventure); copy.turns[copy.turns.length - 1].output = editText; try { await onChange(copy); setEditText(null); } catch(e) { setError((e as Error).message); } }}>Save passage</button></footer></Modal>}</div>;
}
function MemoryPanel({ adventure, onChange, report }: { adventure: Adventure; onChange: (a: Adventure) => Promise<void>; report: (s: string) => void }) {
  const [facts, setFacts] = useState(adventure.facts), [characters, setCharacters] = useState<LaylaCharacter[]>([]), [busy, setBusy] = useState(false), [error, setError] = useState(''), [recall, setRecall] = useState<string[] | null>(null);
  async function action(fn: () => Promise<void>) { setBusy(true); setError(''); try { await fn(); } catch(e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <section><p>Keep the details you don’t want the story to forget.</p><Field label="Adventure facts" hint="Exact, editable notes included in future context. These belong only to this adventure."><textarea rows={7} value={facts} onChange={e => setFacts(e.target.value)}/></Field><button className="button primary" disabled={busy} onClick={() => action(async () => { await onChange({ ...adventure, facts }); report('Adventure memory saved'); })}><Check size={16}/>Save facts</button><hr/><h3><Link2 size={19}/> Layla memory</h3><p className="subtle">Mirror card entries and adventure facts into Layla’s memory. Choose a character to hold them. Wayfarer reads only records marked for this adventure and uses your current private copies as the authority. Card notes and NPC brains stay private.</p>{!characters.length && <button disabled={busy || !hasNativeBridge()} className="button" onClick={() => action(async () => { setCharacters(await withTimeout(signal => layla.characters.list(0, 100, { signal }))); })}>Choose a Layla character</button>}{characters.length > 0 && <Field label="Memory character"><select value={adventure.memoryBinding?.characterId || ''} disabled={busy} onChange={e => action(async () => { const selected = characters.find(c => c.id === e.target.value); if (selected) await onChange({ ...adventure, memoryBinding: { characterId: selected.id, characterName: selected.data.data.name, links: {} } }); })}><option value="">Select character…</option>{characters.map(c => <option key={c.id} value={c.id}>{c.data.data.name}</option>)}</select></Field>}{adventure.memoryBinding && <div className="notice"><strong>Linked to {adventure.memoryBinding.characterName}</strong><p>{adventure.memoryBinding.lastSync ? `Last mirrored ${new Date(adventure.memoryBinding.lastSync).toLocaleString()}` : 'Ready for the first sync.'}</p><div className="toolbar"><button className="button" disabled={busy} onClick={() => action(async () => { const next = await syncMemories({ ...adventure, facts }); await onChange(next.adventure); report(`${next.count} lore and fact memories mirrored to Layla`); })}>{busy ? 'Working…' : 'Sync to Layla'}</button><button className="button" disabled={busy} onClick={() => action(async () => { const memories = await recallMemories(adventure); setRecall(memories.map(m => m.summary || m.rawText)); })}>Check recall</button><button className="text-button" disabled={busy} onClick={() => action(async () => { const copy = clone(adventure); delete copy.memoryBinding; await onChange(copy); })}>Unlink</button></div></div>}{recall && <div className="notice"><strong>{recall.length} current adventure memories returned</strong>{recall.map((text, i) => <p key={i}>{text}</p>)}</div>}{error && <p className="error" role="alert">{error}</p>}<p className="subtle">Sync is manual. Undo and edits take effect in story context immediately; sync again to update Layla’s copies. Unlinking preserves host memories. Host ranking may return no matches.</p></section>;
}
