import { type Scenario, type Store, newScenario } from './domain';
import { importCards } from './cards';
export function seedScenarios(): Scenario[] {
  const definitions = [
    { id: 'seed-hollow', title: 'The Lantern Hollow', genre: 'Cozy fantasy', theme: 'forest' as const, description: 'A borrowed lantern. A missing moon. A village that remembers your name.', opening: 'The last train leaves you at a station the maps have forgotten. Beyond the platform, warm windows glow between enormous roots, and paper lanterns sway in a wind you cannot feel.\n\nA fox in a weather-beaten waistcoat steps out of the ticket office. “You’re late,” he says, handing you a lantern full of blue moths. “The moon went missing three nights ago. We were rather hoping you’d know where to look.”\n\nFrom somewhere under the village, a bell rings once.', memory: 'Lantern Hollow is a hidden woodland village. Its moon vanished three nights ago. You are a newcomer. Gentle wonder, small mysteries, and meaningful choices guide this story.', cards: [{ title: 'Finch', keys: 'fox,Finch,station', type: 'character', value: 'Finch is the fox stationmaster of Lantern Hollow. He is meticulous, warmhearted, and afraid of the dark. He carries a brass watch that runs backward.', description: '' }, { title: 'The Hollow', keys: 'village,Hollow', type: 'location', value: 'Lantern Hollow is built among the roots of an ancient tree. Residents trade in favors and memories. A bell below the tree rings when something lost is found.', description: '' }] },
    { id: 'seed-station', title: 'The Last Signal', genre: 'Science fiction', theme: 'ocean' as const, description: 'An empty station at the edge of known space is calling you home.', opening: 'Your ship catches the signal just as the fuel warning turns amber. It is only seven words: “We kept the lights on for you.”\n\nAhead, Meridian Station turns silently against a pale blue star. It was abandoned twenty years before you were born. Still, the docking arm extends as you approach, and someone has written your name on the arrivals board.\n\nThe airlock indicator changes to green.', memory: 'You are a lone salvage pilot approaching abandoned Meridian Station. The station somehow knows your name. The mystery should unfold gradually with plausible technology and human stakes.', cards: [{ title: 'Meridian Station', keys: 'Meridian,station', type: 'location', value: 'Meridian is a decommissioned research station orbiting a blue star. Its automated systems remain functional. The crew vanished thirty years ago.', description: '' }] },
    { id: 'seed-velvet', title: 'Midnight in Marrow', genre: 'Mystery', theme: 'dusk' as const, description: 'Every guest has a secret. One of them belongs to you.', opening: 'The invitation arrived in your own handwriting. You have never seen it before.\n\nNow you stand beneath the velvet awning of the Marrow Hotel, rain ticking against the brim of your hat. Inside, a pianist plays the same four notes over and over. The concierge slides a key across the desk without asking your name.\n\n“Room thirteen. Your other self checked in an hour ago.”', memory: 'A noir mystery in the rain-soaked city of Marrow. You received an invitation in your own handwriting and arrived at the Marrow Hotel. Your identity and agency belong to the player.', cards: [] },
  ];
  return definitions.map(d => ({ ...newScenario(), ...d, cards: importCards(JSON.stringify(d.cards)).cards }));
}
export const initialStore = (): Store => ({ version: 1, scenarios: seedScenarios(), adventures: [], settings: { maxChars: 12000, fontSize: 18 } });
